-- Bereiche und Schichten pflegen (Lastenheft V-03 bis V-07, Schritt 2.1).
--
-- Bisher war der Bereich nur ein Name an der Schicht ("liste", so heisst er
-- auf helferliste.online). Jetzt ist er eine eigene Zeile mit Beschreibung,
-- Treffpunkt, Leitung, Mindestalter und Voraussetzungen. Die Schicht kennt
-- statt eines Bedarfs drei Zahlen: Minimum, Soll, Reserve.
--
-- Stehen schon Schichten da, wird aus jedem Listennamen ein Bereich, und der
-- bisherige Bedarf wird Soll und Minimum zugleich: mehr wusste das alte Tool
-- nicht.

CREATE TABLE bereich (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL REFERENCES kern.veranstaltung (id),
    name          TEXT NOT NULL,

    -- In einfacher Sprache: was man dort tut. Steht später in der
    -- öffentlichen Anmeldung.
    beschreibung  TEXT NOT NULL DEFAULT '',
    treffpunkt    TEXT NOT NULL DEFAULT '',

    -- Wer vor Ort Bescheid weiß, mit Nummer – für Erinnerungsmail und
    -- Ausdruck (C-02, L-02). Ein Konto wird daraus erst mit der Rolle
    -- Bereichsleitung (B-02).
    leitung       TEXT NOT NULL DEFAULT '',
    leitung_telefon TEXT NOT NULL DEFAULT '',

    -- NULL heißt: keine Altersgrenze.
    mindestalter  INTEGER CHECK (mindestalter IS NULL OR mindestalter BETWEEN 1 AND 99),

    -- Eine je Zeile ("Führerschein Klasse B"). Bei der Anmeldung bestätigt
    -- man jede einzeln.
    voraussetzungen TEXT NOT NULL DEFAULT '',

    -- Nur im Backoffice, nicht in der öffentlichen Anmeldung (V-06).
    intern        INTEGER NOT NULL DEFAULT 0 CHECK (intern IN (0, 1)),

    angelegt_am   TEXT NOT NULL,
    geaendert_am  TEXT,

    UNIQUE (veranstaltung_id, name),
    -- Ziel des Fremdschlüssels aus schicht: so kann eine Schicht nie an
    -- einem Bereich einer anderen Veranstaltung hängen.
    UNIQUE (id, veranstaltung_id)
);

INSERT INTO bereich (veranstaltung_id, name, angelegt_am)
SELECT DISTINCT veranstaltung_id, liste, to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
  FROM schicht;

ALTER TABLE schicht ADD COLUMN bereich_id INTEGER;
UPDATE schicht s SET bereich_id = b.id
  FROM bereich b
 WHERE b.veranstaltung_id = s.veranstaltung_id AND b.name = s.liste;
ALTER TABLE schicht ALTER COLUMN bereich_id SET NOT NULL;
ALTER TABLE schicht ADD FOREIGN KEY (bereich_id, veranstaltung_id)
    REFERENCES bereich (id, veranstaltung_id);

-- Nimmt UNIQUE (veranstaltung_id, liste, beginn, ende) mit.
ALTER TABLE schicht DROP COLUMN liste;

-- Minimum: darunter geht es nicht. Soll: so ist es geplant. Reserve:
-- zusätzlich willkommen, fehlt aber nie (R-01, R-02).
ALTER TABLE schicht RENAME COLUMN bedarf TO soll;
ALTER TABLE schicht
    ADD COLUMN minimum INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN reserve INTEGER NOT NULL DEFAULT 0 CHECK (reserve >= 0),
    -- NULL: es gilt das des Bereichs. Sonst gilt dieses – meist strenger,
    -- niedriger nur bewusst (D-07).
    ADD COLUMN mindestalter INTEGER
        CHECK (mindestalter IS NULL OR mindestalter BETWEEN 1 AND 99),
    -- Intern ist eine Schicht, wenn sie selbst oder ihr Bereich es ist.
    ADD COLUMN intern INTEGER NOT NULL DEFAULT 0 CHECK (intern IN (0, 1));
UPDATE schicht SET minimum = soll;
ALTER TABLE schicht ADD CHECK (minimum >= 0 AND minimum <= soll);
ALTER TABLE schicht ADD UNIQUE (bereich_id, beginn, ende);

CREATE INDEX idx_schicht_bereich ON schicht (bereich_id);

-- Was eine Veranstaltung ihren Helfern bietet (V-07). Danach richtet sich,
-- was die Anmeldung fragt: ohne Shirt keine Größe, ohne Verpflegung keine
-- Verpflegungsfrage (I-02). Fehlt die Zeile, gilt die Vorgabe der Spalten.
-- Angebot und Goodies sind Einstellungen und gehen mit der Veranstaltung;
-- Bereiche halten sie fest wie Schichten und Aufgaben.
CREATE TABLE angebot (
    veranstaltung_id INTEGER PRIMARY KEY
                     REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    -- Ein Helfershirt ab der ersten Schicht.
    shirt         INTEGER NOT NULL DEFAULT 0 CHECK (shirt IN (0, 1)),
    -- Gibt es in der Regel ohnehin; ist kein Goodie.
    verpflegung   INTEGER NOT NULL DEFAULT 1 CHECK (verpflegung IN (0, 1)),
    -- Eine Helferparty für alle nach der Veranstaltung.
    party         INTEGER NOT NULL DEFAULT 0 CHECK (party IN (0, 1)),
    geaendert_am  TEXT
);

-- Kleine Dankeschöns mit Schwelle: "ab 2 Schichten ein Bier am Bierwagen".
-- Mit Altersgrenze bekommt, wer jünger ist, die Alternative (G-02).
CREATE TABLE goodie (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL
                     REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    -- Genau eine der beiden Schwellen.
    ab_schichten  INTEGER CHECK (ab_schichten IS NULL OR ab_schichten >= 1),
    ab_stunden    INTEGER CHECK (ab_stunden IS NULL OR ab_stunden >= 1),
    mindestalter  INTEGER CHECK (mindestalter IS NULL OR mindestalter BETWEEN 1 AND 99),
    alternative   TEXT NOT NULL DEFAULT '',
    angelegt_am   TEXT NOT NULL,
    geaendert_am  TEXT,
    CHECK ((ab_schichten IS NULL) <> (ab_stunden IS NULL))
);

CREATE INDEX idx_goodie_veranstaltung ON goodie (veranstaltung_id);
