-- Die öffentliche Anmeldung (Lastenheft 2.2: A-06 bis A-08, I-01, I-02,
-- I-04, K-01, K-04, R-03, R-05, Interesse vormerken).
--
-- Kein zweites Modell neben dem Backoffice: wer sich selbst anmeldet, steht
-- in denselben Tabellen wie wer importiert oder von Hand eingeteilt wurde –
-- helfer und einteilung. Schichten, Monitor und Ausgabe sehen ihn so ohne
-- Umweg. Neu sind nur, was es vorher nicht gab: die Teilnahme an einer
-- Veranstaltung, Springer-Zeiten und vorgemerktes Interesse.

-- Die Person. Vor- und Nachname getrennt (I-01); `name` bleibt die
-- Anzeige und wird beim Anmelden aus beiden zusammengesetzt.
ALTER TABLE helfer
    ADD COLUMN vorname     TEXT NOT NULL DEFAULT '',
    ADD COLUMN nachname    TEXT NOT NULL DEFAULT '',
    -- NULL: nicht gefragt (Import, von Hand). Unter 18 auch das
    -- Geburtsdatum, für Mindestalter und Elternbestätigung (D-06, D-07).
    ADD COLUMN volljaehrig INTEGER CHECK (volljaehrig IS NULL OR volljaehrig IN (0, 1)),
    ADD COLUMN geburtsdatum TEXT,
    -- Mitangemeldet von (A-08): diese Person bleibt Ansprechpartner.
    ADD COLUMN angemeldet_von INTEGER REFERENCES helfer (id) ON DELETE SET NULL,
    -- Gesetzt, sobald die Adresse per Link bestätigt ist (I-03, Schritt 2.4).
    ADD COLUMN email_bestaetigt_am TEXT;

-- Wer selbst eingetragen hat, und ob als Platz oder als Reserve (R-03).
-- Gezählt wird für „besetzt“ nur der Platz; Reserve fehlt nie (R-02).
ALTER TABLE einteilung DROP CONSTRAINT einteilung_quelle_check;
ALTER TABLE einteilung
    ADD CONSTRAINT einteilung_quelle_check CHECK (quelle IN ('import', 'hand', 'selbst')),
    ADD COLUMN art TEXT NOT NULL DEFAULT 'platz' CHECK (art IN ('platz', 'reserve'));

CREATE INDEX idx_einteilung_art ON einteilung (schicht_id, art);

-- Dass jemand bei einer Veranstaltung mitmacht – auch ohne Schicht, etwa
-- als Springer. Hier steht, was je Veranstaltung neu gefragt wird.
-- Vorlieben sind für den Assistenten (A-03, Phase 3) schon vorgesehen.
CREATE TABLE teilnahme (
    veranstaltung_id INTEGER NOT NULL REFERENCES kern.veranstaltung (id),
    helfer_id     INTEGER NOT NULL REFERENCES helfer (id) ON DELETE CASCADE,
    quelle        TEXT NOT NULL DEFAULT 'selbst' CHECK (quelle IN ('selbst', 'orga', 'import')),
    vorlieben     TEXT[] NOT NULL DEFAULT '{}',
    bemerkung     TEXT NOT NULL DEFAULT '',
    angemeldet_am TEXT NOT NULL,
    PRIMARY KEY (veranstaltung_id, helfer_id)
);

-- Zeitfenster statt Schicht (R-05): „Sa nachmittags, mache alles“. springer
-- heißt: setzt mich ein, wo es brennt. Ohne springer ist es nur
-- Verfügbarkeit, aus der der Assistent Vorschläge macht (A-02).
CREATE TABLE verfuegbarkeit (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL REFERENCES kern.veranstaltung (id),
    helfer_id     INTEGER NOT NULL REFERENCES helfer (id) ON DELETE CASCADE,
    beginn        TEXT NOT NULL,
    ende          TEXT NOT NULL,
    springer      INTEGER NOT NULL DEFAULT 1 CHECK (springer IN (0, 1)),
    angelegt_am   TEXT NOT NULL,
    CHECK (ende > beginn)
);

CREATE INDEX idx_verfuegbarkeit ON verfuegbarkeit (veranstaltung_id, beginn);

-- Interesse an einer angekündigten Veranstaltung (V-02): wer hier steht,
-- bekommt eine Mail, sobald die Anmeldung öffnet (C-08, Schritt 3.3).
CREATE TABLE interesse (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL
                     REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    email         TEXT NOT NULL,
    vorname       TEXT NOT NULL DEFAULT '',
    angelegt_am   TEXT NOT NULL,
    benachrichtigt_am TEXT,
    UNIQUE (veranstaltung_id, email)
);
