-- Einsatzgrenzen (Lastenheft 2.3: K-05 bis K-09).
--
-- Für Helfer mit Einschränkungen, die aus dem Gedanken der Inklusion dabei
-- sind: einen Bereich oder eine Schicht nicht anbieten, einen Bereich nur zu
-- zweit. Die Grenzen wirken still – niemand soll sich ausgeschlossen fühlen.
--
-- Gespeichert wird nur die Grenze, nie der Grund (K-08): keine Diagnose,
-- keine Beschreibung, deshalb gibt es hier auch kein Feld dafür. Was hier
-- steht, könnte die Person lesen – bei einer Auskunft nach Art. 15 DSGVO
-- gehört es dazu.
CREATE TABLE einsatzgrenze (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    helfer_id     INTEGER NOT NULL REFERENCES helfer (id) ON DELETE CASCADE,
    -- Genau eins von beiden: ein ganzer Bereich oder eine Schicht.
    bereich_id    INTEGER REFERENCES bereich (id) ON DELETE CASCADE,
    schicht_id    INTEGER REFERENCES schicht (id) ON DELETE CASCADE,
    art           TEXT NOT NULL CHECK (art IN ('nicht_anbieten', 'nur_zu_zweit')),
    angelegt_von  TEXT NOT NULL DEFAULT '',
    angelegt_am   TEXT NOT NULL,
    CHECK ((bereich_id IS NULL) <> (schicht_id IS NULL)),
    -- „Nur zu zweit“ gilt für einen Bereich; für eine einzelne Schicht
    -- plant die Bereichsleitung ohnehin von Hand.
    CHECK (art = 'nicht_anbieten' OR bereich_id IS NOT NULL),
    -- Je Person und Ziel eine Grenze; eine neue ersetzt die alte.
    UNIQUE NULLS NOT DISTINCT (helfer_id, bereich_id, schicht_id)
);

CREATE INDEX idx_einsatzgrenze_bereich ON einsatzgrenze (bereich_id);
CREATE INDEX idx_einsatzgrenze_schicht ON einsatzgrenze (schicht_id);

-- Die Orga darf trotzdem einteilen (K-09), aber nicht stillschweigend.
ALTER TABLE einteilung ADD COLUMN vermerk TEXT NOT NULL DEFAULT '';

-- Wer was an einer Person geändert hat (K-08). Mit 2.5 schreibt auch die
-- Selbstbedienung hierher. Geht die Person, geht ihr Protokoll mit.
CREATE TABLE protokoll (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    helfer_id     INTEGER NOT NULL REFERENCES helfer (id) ON DELETE CASCADE,
    wer           TEXT NOT NULL DEFAULT '',
    was           TEXT NOT NULL,
    am            TEXT NOT NULL
);

CREATE INDEX idx_protokoll_helfer ON protokoll (helfer_id, am);
