-- Bestätigung, Mein Helferplatz und Mails (Lastenheft 2.4: A-09 bis A-11,
-- I-03, I-05, C-01).
--
-- Die persönlichen Links – Mein Helferplatz, Bestätigen, Kalender – stehen
-- nicht in der Datenbank. Sie sind ein Siegel über Person und Zweck mit dem
-- Schlüssel der App (zugang.py): jede Mail kann denselben Link enthalten,
-- und eine Kopie der Datenbank verrät keinen. Zählt man zugang_version hoch,
-- gilt keiner der alten mehr.
ALTER TABLE helfer
    ADD COLUMN zugang_version INTEGER NOT NULL DEFAULT 0,
    -- Falsch eingetippte Codes; ab fünf gilt nur noch der Link.
    ADD COLUMN code_versuche  INTEGER NOT NULL DEFAULT 0,
    -- Wann an die fehlende Bestätigung erinnert wurde (I-03).
    ADD COLUMN erinnert_am    TEXT;

-- Was verschickt werden soll. Verschickt wird nie in der Anfrage, sondern
-- vom Worker (versand.py) – hängt der Mailserver, hängt sonst das Formular.
-- Wie in Kennzeichen und Presse, nur an der Person statt am Antrag.
CREATE TABLE mail_out (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Geht die Person, gehen ihre ungesendeten Mails mit.
    helfer_id     INTEGER REFERENCES helfer (id) ON DELETE CASCADE,
    typ           TEXT NOT NULL,
    empfaenger    TEXT NOT NULL,
    betreff       TEXT NOT NULL,
    body          TEXT NOT NULL,
    versuche      INTEGER NOT NULL DEFAULT 0,
    gesendet_am   TEXT,
    letzter_fehler TEXT,
    naechster_versuch TEXT,
    angelegt_am   TEXT NOT NULL
);

CREATE INDEX idx_mail_out_offen ON mail_out (gesendet_am, versuche);
