-- Selbstbedienung, Warteliste und Absagen (Lastenheft 2.5: S-01 bis S-08,
-- R-04, B-05).

-- Die Warteliste (R-04) – eine eigene Tabelle statt einer weiteren Art an
-- der Einteilung: so zählt sie nirgends mit, wo Einteilungen gezählt werden
-- (Monitor, Übersicht, Ausfuhr), ohne dass jede Abfrage davon wissen muss.
CREATE TABLE warteliste (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schicht_id    INTEGER NOT NULL REFERENCES schicht (id) ON DELETE CASCADE,
    helfer_id     INTEGER NOT NULL REFERENCES helfer (id) ON DELETE CASCADE,
    angelegt_am   TEXT NOT NULL,
    UNIQUE (schicht_id, helfer_id)
);

CREATE INDEX idx_warteliste_schicht ON warteliste (schicht_id, angelegt_am);

-- Wird ein Platz frei, bekommt die erste Person der Warteliste ihn
-- angeboten: sie steht schon drin und hält ihn bis hierhin. Bestätigt sie,
-- wird es NULL; tut sie es nicht, ist der Platz wieder frei.
ALTER TABLE einteilung ADD COLUMN bestaetigen_bis TEXT;

-- Absagen (S-01, S-03, S-07): wer wann welche Schicht abgegeben hat. Für die
-- Bereichsleitung und die Übersicht – kurzfristige ganz oben. Der Name steht
-- dabei, weil die Person danach oft nicht mehr eingeteilt ist; löscht sie
-- ihre Daten, wird er geleert.
CREATE TABLE absage (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    schicht_id    INTEGER NOT NULL REFERENCES schicht (id) ON DELETE CASCADE,
    helfer_id     INTEGER REFERENCES helfer (id) ON DELETE SET NULL,
    name          TEXT NOT NULL DEFAULT '',
    grund         TEXT NOT NULL DEFAULT '',
    -- Weniger als 24 Stunden vorher oder während der Veranstaltung.
    kurzfristig   INTEGER NOT NULL DEFAULT 0 CHECK (kurzfristig IN (0, 1)),
    am            TEXT NOT NULL
);

CREATE INDEX idx_absage_va ON absage (veranstaltung_id, am);

-- Das Protokoll kennt jetzt Veranstaltung und Bereich – für „Änderungen
-- seit gestern“, das eine Bereichsleitung nur für ihre Bereiche sieht (S-08).
ALTER TABLE protokoll
    ADD COLUMN veranstaltung_id INTEGER REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    ADD COLUMN bereich_id INTEGER REFERENCES bereich (id) ON DELETE SET NULL;

CREATE INDEX idx_protokoll_va ON protokoll (veranstaltung_id, am);

ALTER TABLE helfer
    -- Eine neue Adresse gilt erst, wenn sie bestätigt ist (S-04).
    ADD COLUMN email_neu TEXT,
    -- Löschen gewünscht, aber noch etwas ausgeliehen (S-05): gelöscht wird
    -- nach der Rückgabe.
    ADD COLUMN loeschen_beantragt_am TEXT;
