-- Hilferuf (Lastenheft 3.4: C-03, C-04, C-09, A-12).

ALTER TABLE helfer
    -- C-09: keine Hilferufe und Einladungen mehr. Die Mails zu den eigenen
    -- Schichten kommen weiter – die sind etwas anderes.
    ADD COLUMN aufrufe_abbestellt_am TEXT;

-- C-04: je Schicht höchstens ein Hilferuf per Mail in 24 Stunden. Hier
-- steht, wann für welche Schicht gerufen wurde und wie viele die Mail
-- bekamen. Wer sie bekam, steht in mail_out – nicht noch einmal hier.
CREATE TABLE hilferuf (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL
                     REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    schicht_id    INTEGER NOT NULL REFERENCES schicht (id) ON DELETE CASCADE,
    empfaenger    INTEGER NOT NULL DEFAULT 0,
    wer           TEXT NOT NULL DEFAULT '',
    am            TEXT NOT NULL
);

CREATE INDEX idx_hilferuf_schicht ON hilferuf (schicht_id, am);
