-- Die Materialausgabe verallgemeinert (Lastenheft 3.8, V-09).
--
-- Bisher gab es zwei feste Ausgaben: Funk (ausleihe, mit drei Spalten für
-- Funkgerät, Headset und Ersatzakku) und Schlüssel (schluessel, je Vorgang
-- ein Fahrzeug). Jetzt legt jede Veranstaltung fest, was sie ausgibt – je
-- Material mit oder ohne Rückgabe, mit oder ohne Unterschrift, mit Nummer
-- oder Kennzeichen –, und ausgegeben wird alles auf eine Weise. Funk und
-- Schlüssel sind vier Materialien unter vielen.

-- Was eine Veranstaltung ausgibt.
CREATE TABLE material (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL
                     REFERENCES kern.veranstaltung (id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    -- Kommt es zurück? Ohne Rückgabe (ein Parkausweis, ein Essensbon) ist
    -- ein Vorgang mit der Übergabe erledigt.
    rueckgabe     INTEGER NOT NULL DEFAULT 1 CHECK (rueckgabe IN (0, 1)),
    -- Unterschrift am Tablet bei der Ausgabe.
    unterschrift  INTEGER NOT NULL DEFAULT 1 CHECK (unterschrift IN (0, 1)),
    -- Was je Stück notiert wird: nichts, eine Nummer (Funkgerät 12) oder ein
    -- Kennzeichen (der Fahrzeugstamm baut sich damit auf).
    erfassen      TEXT NOT NULL DEFAULT ''
                  CHECK (erfassen IN ('', 'nummer', 'kennzeichen')),
    -- Womit das Ausgabeformular vorbelegt ist.
    vorgabe       INTEGER NOT NULL DEFAULT 0 CHECK (vorgabe BETWEEN 0 AND 20),
    reihenfolge   INTEGER NOT NULL DEFAULT 0,
    angelegt_am   TEXT NOT NULL,
    UNIQUE (veranstaltung_id, name)
);

-- Ein Vorgang: wer, wann, mit welcher Unterschrift. An Helfer oder an jeden
-- anderen – dann steht nur der Name da.
CREATE TABLE ausgabe (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veranstaltung_id INTEGER NOT NULL REFERENCES kern.veranstaltung (id),
    helfer_id     INTEGER REFERENCES helfer (id) ON DELETE CASCADE,
    -- Wie die Person am Tisch hieß. Bei Helfern zur Anzeige mitgeschrieben,
    -- bei allen anderen das Einzige, was es gibt.
    name          TEXT NOT NULL DEFAULT '',
    -- Für welchen Tag (optional).
    datum         TEXT,
    bemerkung     TEXT NOT NULL DEFAULT '',
    ausgegeben_am TEXT NOT NULL,
    ausgegeben_von TEXT NOT NULL DEFAULT '',
    -- Gesetzt, sobald alles zurück ist, was zurückkommen muss – bei einem
    -- Vorgang ganz ohne Rückgabe gleich bei der Ausgabe.
    zurueck_am    TEXT,
    zurueck_von   TEXT NOT NULL DEFAULT '',
    CHECK (helfer_id IS NOT NULL OR name <> '')
);

CREATE INDEX idx_ausgabe_offen ON ausgabe (veranstaltung_id, zurueck_am);
CREATE INDEX idx_ausgabe_helfer ON ausgabe (helfer_id);

-- Was in einem Vorgang herausging, je Material eine Zeile.
CREATE TABLE ausgabe_posten (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ausgabe_id    INTEGER NOT NULL REFERENCES ausgabe (id) ON DELETE CASCADE,
    -- Ohne CASCADE: ein Material, das schon herausging, lässt sich nicht
    -- löschen – sonst verschwände mit ihm, was jemand unterschrieben hat.
    material_id   INTEGER NOT NULL REFERENCES material (id),
    menge         INTEGER NOT NULL CHECK (menge > 0),
    zurueck       INTEGER NOT NULL DEFAULT 0 CHECK (zurueck >= 0 AND zurueck <= menge),
    -- Nummer oder Kennzeichen, wie angezeigt.
    nummer        TEXT NOT NULL DEFAULT '',
    fahrzeug_id   INTEGER REFERENCES fahrzeug (id)
);

CREATE INDEX idx_ausgabe_posten ON ausgabe_posten (ausgabe_id);
CREATE INDEX idx_ausgabe_posten_material ON ausgabe_posten (material_id);

-- --- Übernahme -------------------------------------------------------------
--
-- Jede Veranstaltung, die die Ausgabe nutzt oder schon etwas ausgegeben hat,
-- bekommt die vier bisherigen Materialien. Die Vorbelegung kommt aus den
-- Einstellungen, wo sie bisher für alle stand.

INSERT INTO material (veranstaltung_id, name, rueckgabe, unterschrift, erfassen,
                      vorgabe, reihenfolge, angelegt_am)
SELECT v.id, m.name, 1, 1, m.erfassen,
       COALESCE((SELECT CASE WHEN e.wert ~ '^[0-9]+$' THEN LEAST(e.wert::int, 20) END
                 FROM einstellung e WHERE e.schluessel = 'vorgabe_' || m.alt), m.vorgabe),
       m.reihenfolge, to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
FROM kern.veranstaltung v
CROSS JOIN (VALUES ('Funkgerät', 'funke', '', 1, 1),
                   ('Headset', 'headset', '', 0, 2),
                   ('Ersatzakku', 'ersatzakku', '', 0, 3),
                   ('Fahrzeugschlüssel', 'schluessel', 'kennzeichen', 0, 4))
           AS m (name, alt, erfassen, vorgabe, reihenfolge)
WHERE 'ausgabe' = ANY (v.nutzt)
   OR EXISTS (SELECT 1 FROM ausleihe a WHERE a.veranstaltung_id = v.id)
   OR EXISTS (SELECT 1 FROM schluessel s WHERE s.veranstaltung_id = v.id);

ALTER TABLE ausgabe ADD COLUMN alt_ausleihe INTEGER, ADD COLUMN alt_schluessel INTEGER;

INSERT INTO ausgabe (veranstaltung_id, helfer_id, name, datum, bemerkung, ausgegeben_am,
                     ausgegeben_von, zurueck_am, zurueck_von, alt_ausleihe)
SELECT a.veranstaltung_id, a.helfer_id, h.name, a.datum, a.bemerkung, a.ausgegeben_am,
       a.ausgegeben_von, a.zurueck_am, a.zurueck_von, a.id
FROM ausleihe a JOIN helfer h ON h.id = a.helfer_id;

INSERT INTO ausgabe_posten (ausgabe_id, material_id, menge, zurueck)
SELECT g.id, m.id, x.menge, x.zurueck
FROM ausleihe a
JOIN ausgabe g ON g.alt_ausleihe = a.id
CROSS JOIN LATERAL (VALUES ('Funkgerät', a.funke, a.funke_zurueck, 1),
                           ('Headset', a.headset, a.headset_zurueck, 2),
                           ('Ersatzakku', a.ersatzakku, a.ersatzakku_zurueck, 3))
           AS x (name, menge, zurueck, reihenfolge)
JOIN material m ON m.veranstaltung_id = a.veranstaltung_id AND m.name = x.name
WHERE x.menge > 0
ORDER BY g.id, x.reihenfolge;

INSERT INTO ausgabe (veranstaltung_id, name, bemerkung, ausgegeben_am, ausgegeben_von,
                     zurueck_am, zurueck_von, alt_schluessel)
SELECT s.veranstaltung_id, CASE WHEN s.name <> '' THEN s.name ELSE f.kennzeichen END,
       s.bemerkung, s.ausgegeben_am, s.ausgegeben_von, s.zurueck_am, s.zurueck_von, s.id
FROM schluessel s JOIN fahrzeug f ON f.id = s.fahrzeug_id;

INSERT INTO ausgabe_posten (ausgabe_id, material_id, menge, zurueck, nummer, fahrzeug_id)
SELECT g.id, m.id, 1, CASE WHEN s.zurueck_am IS NULL THEN 0 ELSE 1 END,
       f.kennzeichen, f.id
FROM schluessel s
JOIN ausgabe g ON g.alt_schluessel = s.id
JOIN fahrzeug f ON f.id = s.fahrzeug_id
JOIN material m ON m.veranstaltung_id = s.veranstaltung_id AND m.name = 'Fahrzeugschlüssel';

-- Die Unterschriften zeigen danach auf die neuen Vorgänge. Erst die vom
-- Material, dann die vom Schlüssel – die werden selbst zu Material.
UPDATE unterschrift u SET vorgang_id = g.id
FROM ausgabe g WHERE u.art = 'material' AND g.alt_ausleihe = u.vorgang_id;
UPDATE unterschrift u SET art = 'material', vorgang_id = g.id
FROM ausgabe g WHERE u.art = 'schluessel' AND g.alt_schluessel = u.vorgang_id;

ALTER TABLE ausgabe DROP COLUMN alt_ausleihe, DROP COLUMN alt_schluessel;
DROP TABLE ausleihe;
DROP TABLE schluessel;
DELETE FROM einstellung WHERE schluessel IN ('vorgabe_funke', 'vorgabe_headset',
                                             'vorgabe_ersatzakku');
