-- Goodies am Check-in-Tisch abhaken (Lastenheft 4.2: G-02, T-03).
--
-- Wer welches Goodie bekommen hat – und was genau: unter der Altersgrenze
-- die Alternative (Eistüte statt Bier). Je Goodie und Person einmal.
CREATE TABLE goodie_ausgabe (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goodie_id     INTEGER NOT NULL REFERENCES goodie (id) ON DELETE CASCADE,
    helfer_id     INTEGER NOT NULL REFERENCES helfer (id) ON DELETE CASCADE,
    was           TEXT NOT NULL,
    ausgegeben_am TEXT NOT NULL,
    ausgegeben_von TEXT NOT NULL DEFAULT '',
    UNIQUE (goodie_id, helfer_id)
);

CREATE INDEX idx_goodie_ausgabe_helfer ON goodie_ausgabe (helfer_id);
