"""Die Übernahme der SQLite-Bestände nach PostgreSQL (deploy/sqlite-uebernehmen.py).

    python tests/test_uebernahme.py

Braucht den PostgreSQL aus compose.yaml. Baut sich drei SQLite-Dateien im
Aufbau des letzten SQLite-Stands – aus den Migrationen selbst, nur in
SQLite-Schreibweise – und übernimmt sie in eine Wegwerf-Datenbank.
"""

import os
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

WURZEL = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(WURZEL))
from kern import testdb  # noqa: E402

PYTHON = WURZEL / ".venv" / "Scripts" / "python.exe"
if not PYTHON.exists():
    PYTHON = WURZEL / ".venv" / "bin" / "python"
if not PYTHON.exists():
    PYTHON = Path(sys.executable)

fehler = []


def pruefe(bedingung, text):
    print(("  ok   " if bedingung else "  FEHL ") + text)
    if not bedingung:
        fehler.append(text)


def sqlite_datei(bereich: str, pfad: Path) -> sqlite3.Connection:
    """Eine SQLite-Datei mit den Tabellen des Bereichs."""
    text = (WURZEL / bereich / "app" / "migrationen" / "0001_anfang.sql").read_text(
        encoding="utf-8")
    text = (text.replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                         "INTEGER PRIMARY KEY")
            .replace("IS DISTINCT FROM", "IS NOT"))
    con = sqlite3.connect(pfad)
    con.executescript(text)
    return con


def lauf(*argumente):
    ergebnis = subprocess.run(
        [str(PYTHON), str(WURZEL / "deploy" / "sqlite-uebernehmen.py"),
         "--url", DB, *argumente],
        capture_output=True, text=True, encoding="utf-8",
        env={**os.environ, "PYTHONIOENCODING": "utf-8"})
    return ergebnis.returncode, ergebnis.stdout + ergebnis.stderr


def sql(schema, befehl, *parameter):
    return testdb.abfrage(DB, schema, befehl, parameter)


DB = testdb.wegwerf("test_uebernahme")
ordner = Path(tempfile.mkdtemp(prefix="uebernahme-"))

# --- Bestände mit Lücken in den Nummern, wie nach dem Löschen ------------------

kfz = sqlite_datei("kennzeichen", ordner / "antraege.db")
with kfz:
    for nummer, name in ((3, "Müller"), (17, "Öztürk")):
        kfz.execute(
            "INSERT INTO antrag (id, vorname, nachname, funktion, kategorie,"
            " kennzeichen, status, created_at) VALUES (?, 'Anna', ?, 'Aufbau',"
            " 'camping', 'KA-AB 1', 'genehmigt', '2026-08-01T10:00:00+00:00')",
            (nummer, name))
    kfz.execute(
        "INSERT INTO mail_out (id, antrag_id, typ, empfaenger, betreff, body,"
        " created_at) VALUES (40, 17, 'orga', 'orga@example.org', 'Neu', 'Text',"
        " '2026-08-01T10:00:00+00:00')")
    kfz.execute("INSERT INTO einstellung VALUES ('durchfahrt_token', 'geheim', '2026-08-01')")
    # Eine Spalte, die es in PostgreSQL nicht gibt - etwa von einem Versuch.
    kfz.execute("ALTER TABLE antrag ADD COLUMN altlast TEXT")
kfz.close()

presse = sqlite_datei("presse", ordner / "presse.db")
with presse:
    presse.execute(
        "INSERT INTO anmeldung (id, vorname, nachname, firma, email, kommerziell,"
        " gegenleistung, sicherheit_ok_am, bildrechte_ok_am, created_at)"
        " VALUES (5, 'Bea', 'Blende', 'Licht GmbH', 'bea@example.org', 1,"
        " 'bilderspende', '2026-08-01', '2026-08-01', '2026-08-01')")
presse.close()

helfer = sqlite_datei("helfer", ordner / "helfer.db")
with helfer:
    helfer.execute(
        "INSERT INTO helfer (id, name, schluessel, angelegt_am, tshirt)"
        " VALUES (8, 'Jörg', 'jörg|', '2026-08-01', '5XL')")
    helfer.execute(
        "INSERT INTO schicht (id, liste, beginn, ende, datum, bedarf, angelegt_am)"
        " VALUES (12, 'Shuttle', '2026-08-29 08:00', '2026-08-29 12:00',"
        " '2026-08-29', 2, '2026-08-01')")
    helfer.execute(
        "INSERT INTO einteilung (id, schicht_id, helfer_id, eingeteilt_am)"
        " VALUES (30, 12, 8, '2026-08-01')")
    helfer.execute("INSERT INTO einstellung VALUES ('monitor_token', 'm-token', '2026-08-01')")
helfer.close()

dateien = ["--kennzeichen", str(ordner / "antraege.db"),
           "--presse", str(ordner / "presse.db"),
           "--helfer", str(ordner / "helfer.db")]

print("Probelauf")
code, ausgabe = lauf(*dateien)
pruefe(code == 0, "läuft durch")
pruefe("Bereit" in ausgabe, "und meldet sich bereit")
pruefe("altlast" in ausgabe and "nicht übernommen" in ausgabe,
       "nennt die Spalte, die es nicht mehr gibt")
pruefe(sql("kennzeichen", "SELECT COUNT(*) FROM antrag")[0][0] == 0,
       "und schreibt nichts fest")

print("Übernahme")
code, ausgabe = lauf(*dateien, "--wirklich")
pruefe(code == 0, "läuft durch: " + ausgabe.strip().splitlines()[-1])
pruefe([z[0] for z in sql("kennzeichen", "SELECT id FROM antrag ORDER BY id")] == [3, 17],
       "die Antragsnummern bleiben, Lücken inklusive")
pruefe(sql("kennzeichen", "SELECT nachname FROM antrag WHERE id = 17")[0][0] == "Öztürk",
       "Umlaute kommen an")
pruefe(sql("kennzeichen", "SELECT antrag_id FROM mail_out WHERE id = 40")[0][0] == 17,
       "die Mail zeigt weiter auf ihren Antrag")
pruefe(sql("kennzeichen", "SELECT wert FROM einstellung")[0][0] == "geheim",
       "der Token der Durchfahrtsliste gilt weiter")
pruefe(sql("presse", "SELECT gegenleistung FROM anmeldung WHERE id = 5")[0][0]
       == "bilderspende", "die Presse-Anmeldung ist da")
pruefe(sql("helfer", "SELECT helfer_id FROM einteilung WHERE id = 30")[0][0] == 8,
       "die Einteilung zeigt weiter auf ihren Helfer")
pruefe(sql("helfer", "SELECT tshirt FROM helfer")[0][0] == "5XL",
       "die Größe, an der SQLite einmal scheiterte, auch")
pruefe(sql("helfer", "SELECT wert FROM einstellung")[0][0] == "m-token",
       "der Monitor-Link gilt weiter")

print("Neue Zeilen danach")
neu = sql("kennzeichen",
          "INSERT INTO antrag (vorname, nachname, funktion, kategorie, created_at)"
          " VALUES ('Neu', 'Person', 'Aufbau', 'camping', '2026-09-01') RETURNING id")
pruefe(neu[0][0] == 18, "der nächste Antrag bekommt 18, nicht 1: %s" % neu[0][0])
neu = sql("helfer",
          "INSERT INTO helfer (name, schluessel, angelegt_am)"
          " VALUES ('Neu', 'neu|', '2026-09-01') RETURNING id")
pruefe(neu[0][0] == 9, "der nächste Helfer bekommt 9: %s" % neu[0][0])
neu = sql("presse",
          "INSERT INTO mail_out (typ, empfaenger, betreff, body, created_at)"
          " VALUES ('eingang', 'x@example.org', 'b', 't', '2026-09-01') RETURNING id")
pruefe(neu[0][0] == 1, "eine leere Tabelle beginnt bei 1")

print("Ein zweiter Lauf verdoppelt nichts")
code, ausgabe = lauf(*dateien, "--wirklich")
pruefe(code != 0, "er bricht ab")
pruefe("nicht leer" in ausgabe, "und sagt warum")
pruefe(sql("kennzeichen", "SELECT COUNT(*) FROM antrag")[0][0] == 3,
       "es bleibt bei drei Anträgen")

print("Ein Verstoss gegen die Regeln rollt alles zurück")
DB = testdb.wegwerf("test_uebernahme")
kaputt = sqlite_datei("helfer", ordner / "kaputt.db")
with kaputt:
    # SQLite prüft Fremdschlüssel nur mit PRAGMA foreign_keys - eine
    # Einteilung ins Leere kann in einer alten Datei also stehen.
    kaputt.execute("INSERT INTO einteilung (id, schicht_id, helfer_id, eingeteilt_am)"
                   " VALUES (1, 99, 99, '2026-08-01')")
kaputt.close()
code, ausgabe = lauf("--kennzeichen", str(ordner / "antraege.db"),
                     "--helfer", str(ordner / "kaputt.db"), "--wirklich")
pruefe(code != 0, "die Übernahme scheitert")
pruefe("nichts übernommen" in ausgabe, "und sagt, dass nichts übernommen ist")
pruefe(sql("kennzeichen", "SELECT COUNT(*) FROM antrag")[0][0] == 0,
       "auch der Bereich, der für sich gepasst hätte, bleibt leer")

print()
if fehler:
    print("FEHLGESCHLAGEN (" + str(len(fehler)) + "):")
    for eintrag in fehler:
        print("  - " + eintrag)
    sys.exit(1)
print("alle Pruefungen bestanden")
