"""Der gemeinsame Datenbankzugriff in kern/db.py.

    python tests/test_kern_db.py

Braucht den PostgreSQL aus compose.yaml (docker compose up -d) und legt
sich darauf eine Wegwerf-Datenbank an.
"""

import sys
import tempfile
from pathlib import Path

WURZEL = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(WURZEL))

from kern import db, testdb  # noqa: E402

fehler = []


def pruefe(bedingung, text):
    print(("  ok   " if bedingung else "  FEHL ") + text)
    if not bedingung:
        fehler.append(text)


print("Platzhalter")
pruefe(db.platzhalter("a = ? AND b = ?") == "a = %s AND b = %s", "? wird %s")
pruefe(db.platzhalter("x = '?' AND y = ?") == "x = '?' AND y = %s",
       "ein Fragezeichen im Text bleibt stehen")
pruefe(db.platzhalter("s LIKE '%Shuttle%' AND n = ?") == "s LIKE '%%Shuttle%%' AND n = %s",
       "ein % wird verdoppelt, auch im Text")
pruefe(db.platzhalter("x = 'it''s ?' AND y = ?") == "x = 'it''s ?' AND y = %s",
       "verdoppeltes Anführungszeichen im Text")

print("Zeilen wie sqlite3.Row")
zeile = db.Zeile(["id", "name", "id"], [7, "Max", 9])
pruefe(zeile["name"] == "Max" and zeile[1] == "Max", "per Name und per Position")
pruefe(zeile["id"] == 7 and zeile[2] == 9, "bei gleichem Namen gewinnt die erste Spalte")
pruefe(dict(zeile) == {"id": 7, "name": "Max"}, "dict(zeile)")

url = testdb.wegwerf("test_kern")
ordner = Path(tempfile.mkdtemp(prefix="migrationen-"))
(ordner / "0001_anfang.sql").write_text(
    "CREATE TABLE ding (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    " name TEXT NOT NULL, aktiv INTEGER NOT NULL DEFAULT 1);", encoding="utf-8")

print("Migrationen")
pruefe(db.migrieren(url, "eins", ordner) == ["0001_anfang.sql"], "erster Lauf spielt ein")
pruefe(db.migrieren(url, "eins", ordner) == [], "zweiter Lauf hat nichts zu tun")
(ordner / "0002_kaputt.sql").write_text(
    "ALTER TABLE ding ADD COLUMN neu TEXT; SELECT * FROM gibt_es_nicht;",
    encoding="utf-8")
try:
    db.migrieren(url, "eins", ordner)
    pruefe(False, "eine kaputte Migration scheitert")
except Exception:
    pruefe(True, "eine kaputte Migration scheitert")
con = db.verbinden(url, "eins")
spalten = [z["column_name"] for z in con.execute(
    "SELECT column_name FROM information_schema.columns"
    " WHERE table_schema = 'eins' AND table_name = 'ding'")]
con.close()
pruefe("neu" not in spalten, "und lässt nichts halb zurück: " + str(spalten))
(ordner / "0002_kaputt.sql").unlink()

print("Schemas trennen die Bereiche")
pruefe(db.migrieren(url, "zwei", ordner) == ["0001_anfang.sql"], "dieselbe Tabelle im zweiten Schema")
with db.Datenbank(lambda: url, "eins", ordner).transaktion() as con:
    con.execute("INSERT INTO ding (name) VALUES (?)", ("in eins",))
con = db.verbinden(url, "zwei")
pruefe(con.execute("SELECT COUNT(*) FROM ding").fetchone()[0] == 0,
       "was in eins steht, sieht zwei nicht")
con.close()

print("Verbindung wie sqlite3")
bereich = db.Datenbank(lambda: url, "eins", ordner)
con = bereich.verbinden()
with con:
    neu = con.execute("INSERT INTO ding (name, aktiv) VALUES (?, ?) RETURNING id",
                      ("Wahr", True)).fetchone()[0]
pruefe(con.execute("SELECT aktiv FROM ding WHERE id = ?", (neu,)).fetchone()[0] == 1,
       "True wird als 1 gespeichert")
try:
    with con:
        con.execute("INSERT INTO ding (name) VALUES (?)", ("weg",))
        raise RuntimeError("Abbruch")
except RuntimeError:
    pass
pruefe(con.execute("SELECT COUNT(*) FROM ding WHERE name = 'weg'").fetchone()[0] == 0,
       "eine Ausnahme im with-Block verwirft")
pruefe(not con.roh.closed, "und die Verbindung bleibt offen")
pruefe(con.execute("SELECT id FROM ding WHERE id = ?", (str(neu),)).fetchone() is not None,
       "eine Zahl als Text findet die Zeile")
pruefe(con.execute("SELECT name FROM ding WHERE name LIKE '%ahr%'").fetchone()["name"] == "Wahr",
       "ein % ohne Parameter bleibt, wie es ist")
con.close()

print()
if fehler:
    print("FEHLGESCHLAGEN (" + str(len(fehler)) + "):")
    for eintrag in fehler:
        print("  - " + eintrag)
    sys.exit(1)
print("alle Pruefungen bestanden")
