-- Persönliche Konten fürs Backoffice (Lastenheft B-01 bis B-04). Schema kern:
-- sie gehören allen drei Bereichen, nicht einem.
--
-- Anders als in den Bereichen sind die Zeitpunkte hier echte Zeitstempel. Es
-- gibt keinen SQLite-Bestand, mit dem es zusammenpassen müsste, und die
-- Abläufe von Sitzung und Einladung prüft die Datenbank selbst gegen now().

CREATE TABLE konto (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,         -- klein geschrieben gespeichert
  name          TEXT NOT NULL,
  -- Landet als "bearbeitet von" in den Daten der Bereiche (B-04). Groß
  -- geschrieben gespeichert, eindeutig ohne Rücksicht auf die Schreibung.
  kuerzel       TEXT NOT NULL,
  rolle         TEXT NOT NULL CHECK (rolle IN ('admin', 'orga', 'lesend')),
  -- Welche Bereiche das Konto sieht. Für Admins ohne Bedeutung: sie sehen
  -- alle drei.
  bereiche      TEXT[] NOT NULL DEFAULT '{}'
                CHECK (bereiche <@ ARRAY['kennzeichen', 'presse', 'helfer']),
  -- Leer, bis die Einladung eingelöst ist. Ein Konto ohne Passwort kann
  -- sich nicht anmelden.
  passwort_hash TEXT,
  aktiv         INTEGER NOT NULL DEFAULT 1 CHECK (aktiv IN (0, 1)),
  angelegt_am   TIMESTAMPTZ NOT NULL DEFAULT now(),
  angelegt_von  TEXT NOT NULL DEFAULT '',
  geaendert_am  TIMESTAMPTZ,
  zuletzt_angemeldet_am TIMESTAMPTZ,
  CHECK (email = lower(email)),
  CHECK (kuerzel = upper(kuerzel) AND kuerzel <> '')
);

CREATE UNIQUE INDEX konto_kuerzel ON konto (kuerzel);

-- Angemeldete Geräte. Im Keks steht ein Zufallswert, hier nur sein Hash:
-- wer die Tabelle liest, kann sich damit nicht anmelden. Weil die Sitzung
-- hier steht und nicht nur im Keks, endet sie sofort, wenn ein Konto
-- gesperrt oder sein Passwort geändert wird.
CREATE TABLE sitzung (
  token_hash    TEXT PRIMARY KEY,
  konto_id      INTEGER NOT NULL REFERENCES konto (id) ON DELETE CASCADE,
  angelegt_am   TIMESTAMPTZ NOT NULL DEFAULT now(),
  laeuft_ab_am  TIMESTAMPTZ NOT NULL
);

CREATE INDEX sitzung_konto ON sitzung (konto_id);

-- Links zum Setzen des Passworts: die Einladung eines neuen Kontos und das
-- Zurücksetzen eines vergessenen Passworts. Auch hier nur der Hash.
CREATE TABLE einladung (
  token_hash    TEXT PRIMARY KEY,
  konto_id      INTEGER NOT NULL REFERENCES konto (id) ON DELETE CASCADE,
  zweck         TEXT NOT NULL CHECK (zweck IN ('einladung', 'zuruecksetzen')),
  angelegt_am   TIMESTAMPTZ NOT NULL DEFAULT now(),
  laeuft_ab_am  TIMESTAMPTZ NOT NULL,
  eingeloest_am TIMESTAMPTZ
);

CREATE INDEX einladung_konto ON einladung (konto_id);
