-- Veranstaltungen als eigene Größe (Lastenheft V-01, V-02, Schritt 1.2).
-- Schema kern: sie gehören allen Bereichen. Bisher hing ein Bereich an genau
-- einer Veranstaltung, die in seiner Konfiguration stand (VERANSTALTUNG,
-- TAGE); der ILRC hat aber mehr als eine, die Helfer braucht.

CREATE TABLE veranstaltung (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,                -- "Die absolute Abfahrt 2027"
  -- Kurz und eindeutig, für Auswahl und Überschriften: "AA 2027".
  kurz          TEXT NOT NULL UNIQUE,
  -- Die Tage der Veranstaltung selbst. Auf- und Abbau liegen davor und
  -- danach und gehören trotzdem dazu - über ihre Schichten.
  beginn        DATE NOT NULL,
  ende          DATE NOT NULL,
  ort           TEXT NOT NULL DEFAULT '',
  beschreibung  TEXT NOT NULL DEFAULT '',
  -- planung: unsichtbar; angekuendigt: sichtbar, Interesse vormerkbar;
  -- offen: Anmeldung läuft; geschlossen; archiviert: nur noch Vorlage.
  status        TEXT NOT NULL DEFAULT 'planung'
                CHECK (status IN ('planung', 'angekuendigt', 'offen',
                                  'geschlossen', 'archiviert')),
  anmeldung_ab  DATE,
  anmeldung_bis DATE,
  angelegt_am   TIMESTAMPTZ NOT NULL DEFAULT now(),
  geaendert_am  TIMESTAMPTZ,
  CHECK (ende >= beginn),
  CHECK (anmeldung_ab IS NULL OR anmeldung_bis IS NULL OR anmeldung_bis >= anmeldung_ab)
);

CREATE INDEX veranstaltung_beginn ON veranstaltung (beginn);
