-- Die Kennzeichen-Datenbank, wie sie unter SQLite zuletzt aussah – samt
-- allem, was dort per Umbau dazukam (Mailtyp 'orga', naechster_versuch,
-- keine Kontaktpflicht mehr in der Tabelle). Laeuft im Schema kennzeichen.
--
-- Zeitpunkte bleiben Text in ISO-8601, wie bisher: sie sortieren richtig,
-- und der Code vergleicht sie als Zeichenketten.

CREATE TABLE antrag (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vorname     TEXT NOT NULL,
  nachname    TEXT NOT NULL,
  funktion    TEXT NOT NULL,
  kategorie   TEXT NOT NULL,                    -- Schluessel aus KATEGORIEN (Env)
  email       TEXT,
  telefon     TEXT,
  kennzeichen TEXT,                             -- amtliches Kfz-Kennzeichen
  bemerkung   TEXT,
  status      TEXT NOT NULL DEFAULT 'neu'
              CHECK (status IN ('neu', 'genehmigt', 'abgelehnt', 'ausgegeben')),
  entscheidung_am    TEXT,
  entscheidung_durch TEXT,                      -- Kuerzel
  begruendung        TEXT,                      -- Pflicht bei Ablehnung
  tel_informiert_am  TEXT,                      -- fuer Antraege ohne Mailadresse
  created_at  TEXT NOT NULL,
  remote_ip   TEXT                              -- nur fuer Missbrauchsfaelle
  -- Keine CHECK-Bedingung auf E-Mail oder Telefon: die Regel steht in
  -- validation.pruefen(), wo sie an die Lage gebunden werden kann. Wer am
  -- Tisch steht und sofort genehmigt wird, hat nichts zu empfangen.
);

CREATE INDEX idx_antrag_status     ON antrag (status);
CREATE INDEX idx_antrag_kategorie  ON antrag (kategorie);
CREATE INDEX idx_antrag_created_at ON antrag (created_at);

CREATE TABLE mail_out (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  antrag_id   INTEGER REFERENCES antrag (id) ON DELETE CASCADE,
  typ         TEXT NOT NULL
              CHECK (typ IN ('eingang', 'genehmigt', 'abgelehnt', 'orga')),
  empfaenger  TEXT NOT NULL,
  betreff     TEXT NOT NULL,
  body        TEXT NOT NULL,
  versuche    INTEGER NOT NULL DEFAULT 0,
  gesendet_am TEXT,
  letzter_fehler TEXT,
  naechster_versuch TEXT,             -- Backoff: fruehestens ab diesem Zeitpunkt
  created_at  TEXT NOT NULL
);

CREATE INDEX idx_mail_out_offen ON mail_out (gesendet_am, versuche);

-- Was sich zur Laufzeit aendern laesst und deshalb nicht in die Env gehoert:
-- der Token der offenen Durchfahrtsliste, die Adresse fuer Meldungen.
CREATE TABLE einstellung (
  schluessel   TEXT PRIMARY KEY,
  wert         TEXT NOT NULL,
  geaendert_am TEXT NOT NULL
);
